#!/bin/bash
# Simple dmenu search tool

keywords=("google" "yt" "kat" "aur" "imdb" "duck" "felirat" "rarbg" "open" "~" "/")
hist_file=/tmp/dms_hist

_open(){

    xdg-open $1

}

_keywords(){

    for i in ${keywords[@]}; do
        echo $i
    done
}

dmenu_keywords=$(_keywords | dmenu -l 5 -i -fn 'monospace-12' )

if [[ ! -e $hist_file ]]; then
    touch $hist_file
fi
echo $dmenu_keywords

if ! grep -q "$dmenu_keywords" "$hist_file" && [[ "$dmenu_keywords" != "${keywords[@]}" ]]; then
    echo $dmenu_keywords >> $hist_file
fi

case $dmenu_keywords in


     # Search on Google, Youtube, Kickass, IMDb, DuckDuckGo, feliratok.hu, rarbg.to, AUR
    google*|yt*|kat*|imdb*|duck*|felirat*|rarbg*|aur* )

        search=$(echo $dmenu_keywords | awk '{ if ($1 ~ /(google|yt|kat|imdb|duck|felirat|rarbg|open)/) {$1="" ; gsub(" ","+")} else if ($1 ~ aur) {$1=""; gsub(" ","")}; print $0}')

        if [[ $dmenu_keywords =~ "google" ]]; then
            _open "https://www.google.com/search?q="$search""
        elif [[ $dmenu_keywords =~ "yt" ]]; then
            _open "https://www.youtube.com/results?search_query="$search""
        elif [[ $dmenu_keywords =~ "kat" ]]; then
            _open "https://kat.cr/usearch/?q="$search""
        elif [[ $dmenu_keywords =~ "imdb" ]]; then
            _open "http://www.imdb.com/find?ref_=nv_sr_fn&q="$search"&s=all"
        elif [[ $dmenu_keywords =~ "duck" ]]; then
            _open "https://duckduckgo.com/?q="$search""
        elif [[ $dmenu_keywords =~ "felirat" ]]; then
            _open "http://feliratok.info/?search="$search""
        elif [[ $dmenu_keywords =~ "rarbg" ]]; then
            _open "https://rarbg.to/torrents.php?search="$search""
        elif [[ $dmenu_keywords =~ "aur" ]]; then
            _open "https://www.archlinux.org/packages/?sort=&q="$search"&maintainer=&flagged="
        fi
        ;;

    ~*) # Search local files in home directory and copy selected path to clipboard
        search_result=$(sed -e s"/~//" <<< $dmenu_keywords)
        find ~ -iname $search_result\* | dmenu -l 10 -i -fn 'monospace-12' | xsel -b
        ;;


    open*) # Search local files in home directory and open selected one with default application
        search_result=$(sed -e s"/open//" <<< $dmenu_keywords)
        selected_result=$(find ~ -iname $search_result\* | dmenu -l 10 -i -fn 'monospace-12')
        xdg-open $selected_result
        ;;

    /*) selected_history_element=$(tac $hist_file | dmenu -l 10 -i -fn 'monospace-12')
        search=$(echo $selected_history_element | awk '{ if ($1 ~ /(google|yt|kat|imdb|duck|felirat|rarbg|open)/) {$1="" ; gsub(" ","+")} else if ($1 ~ aur) {$1=""; gsub(" ","")}; print $0}')

        if [[ $selected_history_element =~ "google" ]]; then
            _open "https://www.google.com/search?q="$search""
        elif [[ $selected_history_element =~ "yt" ]]; then
            _open "https://www.youtube.com/results?search_query="$search""
        elif [[ $selected_history_element =~ "kat" ]]; then
            _open "https://kat.cr/usearch/?q="$search""
        elif [[ $selected_history_element =~ "imdb" ]]; then
            _open "http://www.imdb.com/find?ref_=nv_sr_fn&q="$search"&s=all"
        elif [[ $selected_history_element =~ "duck" ]]; then
            _open "https://duckduckgo.com/?q="$search""
        elif [[ $selected_history_element =~ "felirat" ]]; then
            _open "http://feliratok.info/?search="$search""
        elif [[ $selected_history_element =~ "rarbg" ]]; then
            _open "https://rarbg.to/torrents.php?search="$search""
        elif [[ $selected_history_element =~ "aur" ]]; then
            _open "https://www.archlinux.org/packages/?sort=&q="$search"&maintainer=&flagged="
        elif [[ $selected_history_element =~ "open" ]]; then
            search_result=$(sed -e s"/open//" <<< $selected_history_element)
            selected_result=$(find ~ -iname $search_result\* | dmenu -l 10 -i -fn 'monospace-12')
            xdg-open $selected_result
        fi
        ;;

    *) # if no search engine selected, then search automatically on google
        if [[ $dmenu_keywords != "" ]];then

            search_text=$(sed -e "s/\s/+/g" <<< $dmenu_keywords)

           _open "https://www.google.com/search?q="$search_text""

       else
               :

       fi
        ;;

esac
