#!/bin/bash
# Simple dmenu search tool

keywords=("google" "yt" "kat" "aur" "imdb" "duck" "wiki" "felirat" "rarbg" "~")

_open(){

    xdg-open $1

}

_keywords(){

    for i in ${keywords[@]}; do
        echo $i
    done
}

dmenu_keywords=$(_keywords | dmenu -l 5 -i -fn 'monospace-12' )

echo $dmenu_keywords


case $dmenu_keywords in

    google*) # Search on Google
        search_text=$(sed -e s"/google//;s/\s/+/g" <<< $dmenu_keywords)
        
        _open "https://www.google.com/search?q="$search_text""
        ;;


    yt*) # Search on Youtube
        search_text=$(sed -e s"/yt//;s/\s/+/" <<< $dmenu_keywords)

        _open "https://www.youtube.com/results?search_query="$search_text""
        ;;

    kat*) # Search on Kickass Torrents
        search_text=$(sed -e s"/kat//;s/\s/+/" <<< $dmenu_keywords)
       
        _open "https://kat.cr/usearch/?q="$search_text""
        ;;

    imdb*) # Search on IMDb

        search_text=$(sed -e s"/imdb//;s/\s/+/" <<< $dmenu_keywords)

        _open "http://www.imdb.com/find?ref_=nv_sr_fn&q="$search_text"&s=all"
        ;;
    
    duck*) # Search on DuckDuckGo

        search_text=$(sed -e s"/duck//;s/\s/+/g" <<< $dmenu_keywords)

        _open "https://duckduckgo.com/?q="$search_text""
        ;;

    wiki*) # Search on Wikipedia
        search_text=$(sed -e s"/wiki//;s/\s/_/g" <<< $dmenu_keywords)

        _open "https://en.wikipedia.org/wiki/"$search_text""
        ;;

    felirat*) # Search on feliratok.hu
        search_text=$(sed -e s"/felirat//;s/\s/+/g" <<< $dmenu_keywords)

        _open "http://feliratok.info/?search="$search_text""
        ;;

    rarbg*) # Search on rarbg.to
        search_text=$(sed -e s"/rarbg//;s/\s/+/g" <<< $dmenu_keywords)

        _open "https://rarbg.to/torrents.php?search="$search_text""
        ;;

    aur*) # Search on Arch User Repository
        search_text=$(sed -e s"/aur//;s/\s//g" <<< $dmenu_keywords)

        _open "https://www.archlinux.org/packages/?sort=&q="$search_text"&maintainer=&flagged="
        ;;
        

    ~*) # Search local files in home directory
        search_result=$(sed -e s"/~//" <<< $dmenu_keywords)

        # If no string typed for search, just tilde (~) selected...
        if [[ $search_result = "" ]]; then

            # ... then open selected file
            selected_result=$(find ~ -iname $search_result\* | dmenu -l 10 -i -fn 'monospace-12')
            xdg-open $selected_result

        else
            # If string typed for searhc, then search it in home directory, then copy the selected file's path into clipboard

            find ~ -iname $search_result\* | dmenu -l 10 -i -fn 'monospace-12' | xsel -b

        fi
        ;;

    *) # if no search engine selected, then search automatically on google

        if [[ $dmenu_keywords != "" ]];then

            search_text=$(sed -e "s/\s/+/g" <<< $dmenu_keywords)
        
           _open "https://www.google.com/search?q="$search_text""

       else
               :

       fi
        ;;

esac
