#!/bin/bash
# Select media (video) file from dmenu and play it with mpv
# Download subtitle with periscope (https://github.com/patrickdessalle/periscope)


file_name=$( (find ~/downloads -iname "*.mkv" && find ~/downloads -iname "*.mp4" && find ~/downloads -iname "*.srt") | awk -F "/" '{print $NF}' | dmenu -i -l 20 -fn 'monospace-12' )

if [[ "$file_name" == *[\[\]]* ]]; then
    file_name=$(sed 's/\[/\\[/g;s/\]/\\]/g' <<< $file_name)
fi

if [[ $file_name == "" ]]; then
    exit
fi

selected_file=$(find -iname $file_name)

if [[ ! -e $(find ~/downloads -iname ${file_name%.mp4}.srt) ]] && [[ ! -e $(find ~/downloads -iname ${file_name%.mkv}.srt) ]]; then
    subtitle=$(echo "Download subtitle before start?" | dmenu -i -l 1 -fn 'monospace-12')

    case $subtitle in
        yes) periscope -l en $(find ~/downloads -iname $file_name) ; mpv $selected_file;;
        no) mpv $selected_file
    esac

else
    mpv $selected_file
fi
