#!/bin/bash

LVDS1=$(xrandr | grep "1280x800      60.00*")
MON=$(xrandr | grep "VGA1 connected 1280x1024")
TV=$(xrandr | grep "VGA1 connected 1360x768")
DISCON=$(xrandr | grep "VGA1 disconnected")
#ACTIVE=$(xrandr | grep "\*")

if [[ "$LVDS1" ]]; then
    xrandr --output LVDS1 --off --output VGA1 --auto
elif [[ "$MON" ]]; then
    xrandr --output VGA1 --mode 1360x768
elif [[ "$TV" ]]; then
    xrandr --output VGA1 --mode 1280x800
fi
if [[ "$DISCON" ]]; then
    xrandr --output LVDS1 --auto
fi
