#!/bin/bash

LVDS1="1280x800"
VGA1="1280x1024"
ACTIVE=$(xrandr | grep "\*")

if [[ "$ACTIVE" == *"$LVDS1"* ]]; then
    xrandr --output LVDS1 --off --output VGA1 --auto

elif [[ "$ACTIVE" == *"$VGA1"* ]]; then
    xrandr --output LVDS1 --auto --output VGA1 --off
elif [[ "$ACTIVE" != *"$VGA1"* ]] &&  [[ "$ACTIVE" != *"$LVDS1"* ]]; then
    xrandr --output LVDS1 --auto --output VGA1 --off
fi

