#!/bin/bash
#Switch monitor script

check_res=$(xrandr | grep Screen | awk '{print $8}')
check_vga=$(xrandr | grep VGA1 | awk '{print $2}') 

if [[ $check_res = "1280" ]]; then
	if [[ $check_vga = "connected" ]]; then
        xrandr --output VGA1 --auto && xrandr --output LVDS1 --off
        sh ~/.fehbg
	else
		notify-send "Swtich Monitor Script" "Plug in your monitor"
	fi
elif [[ $check_res = "1680" ]]; then
	xrandr --output LVDS1 --auto && xrandr --output VGA1 --off
    sh ~/.fehbg
else
	notify-send "Switch Monitor Script" "Something went wrong.\nCheck the resolution settings in your script"
fi
